#!/bin/bash

set -eu

function usage() {
  cat <<EOF
Usage: compete <subcommand> [options]

Subcommands:
  new       Create a new contest environment.
  test      Test a solution file against sample cases.
  submit    Submit a solution file.
  login     Log in to AtCoder and Codeforces.
  config    Manage configuration.
EOF
  exit 1
}

# シンボリックリンクを解決して、スクリプト本体の真のパスを取得
TRUE_SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$TRUE_SCRIPT_PATH")
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

CONFIG_FILE="$REPO_ROOT/config.default"

# 見つかった設定ファイルを読み込む
source "$CONFIG_FILE"

# サブコマンドに引き継ぎたい変数を export する
export SOLUTIONS_DIR
export DEFAULT_LANG_PRIORITY
export CPP_FLAGS
export ACC_TEMPLATE_DIR

# サブコマンドを取得
SUBCOMMAND=${1:-}
if [ -z "$SUBCOMMAND" ]; then
  usage
fi
shift # サブコマンド名を引数リストから削除

# サブコマンドに応じて処理を振り分ける
case $SUBCOMMAND in
  new | test | submit | login | config)
    "$SCRIPT_DIR"/compete-"$SUBCOMMAND".sh "$@"
    ;;
  *)
    usage
    ;;
esac
