#!/bin/bash

set -eu

function usage() {
  cat <<EOF
Usage: compete <subcommand> [options]

Subcommands:
  new       Create a new contest environment.
  fetch     Fetch sample cases for the current problem.
  test      Test a solution file against sample cases.
  submit    Submit a solution file.
  login     Log in to AtCoder and Codeforces.
  config    Manage configuration.
EOF
  exit 1
}

# シンボリックリンクを解決して、スクリプト本体の真のパスを取得
TRUE_SCRIPT_PATH=$(readlink -f "$0")
SCRIPT_DIR=$(dirname "$TRUE_SCRIPT_PATH")
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

CONFIG_FILE="$REPO_ROOT/config.default"

# 見つかった設定ファイルを読み込む
source "$CONFIG_FILE"

# サブコマンドを取得
SUBCOMMAND=${1:-}
if [ -z "$SUBCOMMAND" ]; then
  usage
fi
shift # サブコマンド名を引数リストから削除

# サブコマンドに応じて処理を振り分ける
case $SUBCOMMAND in
  new | fetch | test | submit | login | config)
    "$(dirname "$0")"/compete-"$SUBCOMMAND".sh "$@"
    ;;
  *)
    usage
    ;;
esac
